# === Makefile.web ===

CC = clang
CFLAGS = -O0 -std=gnu17 -Wall -Wno-unused -Wshadow -Werror --target=wasm32-wasi
INCLUDES = -Isrc -D_WASM
LDFLAGS = 
SRC_DIR = ./src
BUILD_DIR = ./build
TARGET = $(BUILD_DIR)/Main.wasm

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))

all: $(BUILD_DIR) $(TARGET)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) $(SRCS) -o $(TARGET) $(LDFLAGS)

exe: $(TARGET)
	wasmtime $(TARGET)

clean:
	rm -f $(BUILD_DIR)/*

do: clean all exe

# === Makefile.web ===